---

disk:
  device: "/dev/sdb"
  new_partition_table: True

  partitions:
    - create_partition: True
      label: "efi"
      dev: "/dev/sdb1"
      flag: "ef00"
      size: "+1G"
      fs: "fat32"
      mount_point: "/boot"

    - create_partition: True
      label: "root"
      dev: "/dev/sdb2"
      flag: "8300"
      size: "0"
      fs: "btrfs"
      
      subvolumes:
        - name: "@arch"
          mount_point: "/"
          mount_args: "compress=zstd:1,noatime,space_cache=v2,ssd"

        - name: "@arch-home"
          mount_point: "/home"
          mount_args: "compress=zstd:1,noatime,space_cache=v2,ssd"

        - name: "@snapshots"
          mount_point: "/.snapshots"
          mount_args: "compress=zstd:1,noatime,space_cache=v2,ssd"

system:

  pkgs:
    - base
    - base-devel
    - linux-zen
    - linux-zen-headers
    - amd-ucode
    - linux-firmware
    - sof-firmware
    - btrfs-progs
    - iwd
    - sudo
    - vim
    - git

  time_zone: "Asia/Krasnoyarsk"
  locales:
    - en_US.UTF-8 UTF-8
    - ru_RU.UTF-8 UTF-8
  language: "en_US.UTF-8"

  root_password: "1111"

user:
  user_name: "oversky"
  user_password: "555555"
  user_groups:
    - wheel
  user_shell: "/bin/bash"